name: Node CI

on:
  push:
    branches:
      - tag

jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm lint
      - run: npm test 
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
